### ISSUE TITLE
txt - loc dönüşümü

### ISSUE THREAD

**Issue by ThisRock84** [ahmet-celik/watch-dogs-loc-tool#1]
Merhaba,
Loc - Txt dönüşümü çok güzel fakat tam tersini yapmak istediğimiz zaman için bir yöntem geliştirmenizi isteyebilir miyiz?
Lütfen :(

**Comment by ahmet-celik** [comment]
Öyle bir planım yok.

**Comment by ThisRock84** [comment]
Canın sağolsun, emeğine, eline, bilgine sağlık. Çok teşekkürler...
